version: "3.7"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: bioma_deploy
            MYSQL_ROOT_PASSWORD: example

    api:
        depends_on:
            - db
        build: .
        command: yarn dev
        ports: 
           - "3333:3333"
        volumes: 
            - .:/usr/app
