import PropertyAvaliation from '../models/PropertyAvaliationsModel';
import propertyView from './propertyView';

export default {
    render(avaliation: PropertyAvaliation) {
        return {
            id: avaliation.id,
            owner_name: avaliation.owner_name,
            owner_nick: avaliation.owner_nick,
            owner_phone: avaliation.owner_phone,
            owner_school: avaliation.owner_school,
            owner_references: avaliation.owner_references,
            property_name: avaliation.property_name,
            property_area: avaliation.property_area,
            property_value: avaliation.property_value,
            property_location: avaliation.property_location,
            property_city: avaliation.property_city,
            property_state: avaliation.property_state,
            property_router: avaliation.property_router,
            property_distancy: avaliation.property_distancy,
            property_access: avaliation.property_access,
            property_winter_access: avaliation.property_winter_access,
            property_summer_access: avaliation.property_summer_access,
            property_owner: avaliation.property_owner,
            property_topography: avaliation.property_topography,
            property_texture: avaliation.property_texture,
            cover_mec: avaliation.cover_mec,
            cover_mec_species: avaliation.cover_mec_species,
            cover_mec_weeds: avaliation.cover_mec_weeds,
            cover_toco: avaliation.cover_toco,
            cover_toco_species: avaliation.cover_toco_species,
            cover_toco_weeds: avaliation.cover_toco_weeds,
            cover_grass: avaliation.cover_grass,
            cover_grass_species: avaliation.cover_grass_species,
            cover_agriculture: avaliation.cover_agriculture,
            cover_culture: avaliation.cover_culture,
            cover_productivity: avaliation.cover_productivity,
            fency_smooth: avaliation.fency_smooth,
            fency_barbed: avaliation.fency_barbed,
            salt_through: avaliation.salt_through,
            main_house: avaliation.main_house,
            main_house_value: avaliation.main_house_value,
            secondary_house: avaliation.secondary_house,
            secondady_house_value: avaliation.secondady_house_value,
            corral: avaliation.corral,
            corral_value: avaliation.corral_value,
            energy: avaliation.energy,
            energy_type: avaliation.energy_type,
            energy_kva: avaliation.energy_kva,
            weir: avaliation.weir,
            dam: avaliation.dam,
            well_amaz: avaliation.well_amaz,
            well_artesian: avaliation.well_artesian,
            drinking: avaliation.drinking,
            river: avaliation.river,
            river_type: avaliation.river_type,
            river_name: avaliation.river_name,
            market_calf: avaliation.market_calf,
            market_cow: avaliation.market_cow,
            market_ox: avaliation.market_ox,
            market_milk: avaliation.market_milk,
            notes: avaliation.notes,
            property: avaliation.property && propertyView.render(avaliation.property),
        }
    },

    renderMany(avaliations: PropertyAvaliation[]) {
        return avaliations.map(avaliation => this.render(avaliation));
    }
}